### ISSUE TITLE
Add description to README.md

### ISSUE THREAD

**Issue by davelab6** [kelvin13/a-font-named-font#1]
Please add a README.md file with a description of the design.

**Comment by tayloraswift** [comment]
Done: added a short description and a screenshot of the font in use

**Comment by davelab6** [comment]
Its still a bit short - compare to eg https://www.google.com/fonts/specimen/Glegoo

**Comment by davelab6** [comment]
Also I've now put together https://github.com/googlefonts/gf-docs/blob/master/ProjectChecklist.md which I hope can help :)

**Comment by tayloraswift** [comment]
Okay, I can put together a description like that, but why are we putting the release components in this repository? a-font-named-font only holds the latin fraction of the font, why not combine with https://github.com/appajid/Kelvin-Kannada

**Comment by tayloraswift** [comment]
And have we agreed that the release name of the font is “Ambarisha” correct?

**Comment by davelab6** [comment]
Yes. I agree, best thing is you work on that repo directly. You are both using FontForge :)
